"""migrate_gpa_to_cgpa

Revision ID: 22a94df0111d
Revises: 6b5b7e1e0407
Create Date: 2026-04-01 19:13:17.412514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a94df0111d'
down_revision: Union[str, Sequence[str], None] = '6b5b7e1e0407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cgpa', sa.Float(), nullable=True))
    op.drop_column('users', 'gpa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'cgpa')
    # ### end Alembic commands ###
