"""Merge GenAIFinal enhancements

Revision ID: 3c9f58d8f91f
Revises: 4e3967430dc1
Create Date: 2026-04-21 14:58:18.097382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9f58d8f91f'
down_revision: Union[str, Sequence[str], None] = '4e3967430dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_degrees_id'), table_name='user_degrees')
    op.drop_table('user_degrees')
    op.drop_index(op.f('ix_user_tests_id'), table_name='user_tests')
    op.drop_table('user_tests')
    op.add_column('universities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('acceptance_rate', sa.Float(), nullable=True))
    op.add_column('universities', sa.Column('intake_months', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('field_of_study', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_degree', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_degree', sa.String(), nullable=True))
    op.add_column('users', sa.Column('home_university', sa.String(), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('english_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('english_test', sa.String(), nullable=True))
    op.add_column('users', sa.Column('toefl_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gre_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gmat_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('budget_inr', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('intake_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ranking_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('scholarship_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('work_abroad_interest', sa.Boolean(), nullable=True))
    op.alter_column('users', 'work_experience_years',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('users', 'preferred_environment')
    op.drop_column('users', 'career_goal')
    op.drop_column('users', 'living_preference')
    op.drop_column('users', 'preferred_intake')
    op.drop_column('users', 'learning_style')
    op.drop_column('users', 'study_priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('learning_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_intake', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('living_preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('career_goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_environment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'work_experience_years',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('users', 'work_abroad_interest')
    op.drop_column('users', 'scholarship_interest')
    op.drop_column('users', 'ranking_preference')
    op.drop_column('users', 'intake_preference')
    op.drop_column('users', 'budget_inr')
    op.drop_column('users', 'gmat_score')
    op.drop_column('users', 'gre_score')
    op.drop_column('users', 'toefl_score')
    op.drop_column('users', 'english_test')
    op.drop_column('users', 'english_score')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'home_university')
    op.drop_column('users', 'current_degree')
    op.drop_column('users', 'preferred_degree')
    op.drop_column('users', 'field_of_study')
    op.drop_column('users', 'cgpa')
    op.drop_column('users', 'full_name')
    op.drop_column('universities', 'intake_months')
    op.drop_column('universities', 'acceptance_rate')
    op.drop_column('universities', 'description')
    op.create_table('user_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('test_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_tests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_tests_pkey'))
    )
    op.create_index(op.f('ix_user_tests_id'), 'user_tests', ['id'], unique=False)
    op.create_table('user_degrees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('degree_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('institution', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year_graduated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_degrees_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_degrees_pkey'))
    )
    op.create_index(op.f('ix_user_degrees_id'), 'user_degrees', ['id'], unique=False)
    # ### end Alembic commands ###
