"""Sync schema missing columns

Revision ID: 4e3967430dc1
Revises: 22a94df0111d
Create Date: 2026-04-21 14:33:56.217871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3967430dc1'
down_revision: Union[str, Sequence[str], None] = '22a94df0111d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('degree_level', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('year_graduated', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_degrees_id'), 'user_degrees', ['id'], unique=False)
    op.create_table('user_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('test_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tests_id'), 'user_tests', ['id'], unique=False)
    op.add_column('universities', sa.Column('qs_subject_ranking', sa.Integer(), nullable=True))
    op.add_column('universities', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('universities', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('universities', sa.Column('website', sa.String(), nullable=True))
    op.add_column('universities', sa.Column('requirements_cgpa', sa.Float(), nullable=True))
    op.add_column('universities', sa.Column('ielts', sa.Float(), nullable=True))
    op.add_column('universities', sa.Column('toefl', sa.Integer(), nullable=True))
    op.add_column('universities', sa.Column('gre_required', sa.Boolean(), nullable=True))
    op.add_column('universities', sa.Column('scholarships', sa.String(), nullable=True))
    op.add_column('universities', sa.Column('course_duration', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_universities_subject'), 'universities', ['subject'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('work_experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferred_intake', sa.String(), nullable=True))
    op.add_column('users', sa.Column('career_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_environment', sa.String(), nullable=True))
    op.add_column('users', sa.Column('study_priority', sa.String(), nullable=True))
    op.add_column('users', sa.Column('learning_style', sa.String(), nullable=True))
    op.add_column('users', sa.Column('living_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'cgpa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp')
    op.drop_column('users', 'living_preference')
    op.drop_column('users', 'learning_style')
    op.drop_column('users', 'study_priority')
    op.drop_column('users', 'preferred_environment')
    op.drop_column('users', 'career_goal')
    op.drop_column('users', 'preferred_intake')
    op.drop_column('users', 'work_experience_years')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_universities_subject'), table_name='universities')
    op.drop_column('universities', 'course_duration')
    op.drop_column('universities', 'scholarships')
    op.drop_column('universities', 'gre_required')
    op.drop_column('universities', 'toefl')
    op.drop_column('universities', 'ielts')
    op.drop_column('universities', 'requirements_cgpa')
    op.drop_column('universities', 'website')
    op.drop_column('universities', 'image_url')
    op.drop_column('universities', 'subject')
    op.drop_column('universities', 'qs_subject_ranking')
    op.drop_index(op.f('ix_user_tests_id'), table_name='user_tests')
    op.drop_table('user_tests')
    op.drop_index(op.f('ix_user_degrees_id'), table_name='user_degrees')
    op.drop_table('user_degrees')
    # ### end Alembic commands ###
