"""add_extended_indian_student_profile

Revision ID: ebe6c6559505
Revises: a1b2c3d4e5f6
Create Date: 2026-04-19 18:08:19.937908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebe6c6559505'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_table('appointments')
    op.create_index(op.f('ix_universities_subject'), 'universities', ['subject'], unique=False)
    op.add_column('users', sa.Column('current_degree', sa.String(), nullable=True))
    op.add_column('users', sa.Column('home_university', sa.String(), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('english_test', sa.String(), nullable=True))
    op.add_column('users', sa.Column('toefl_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gre_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gmat_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('work_experience_years', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('budget_inr', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('intake_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ranking_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('scholarship_interest', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('work_abroad_interest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_abroad_interest')
    op.drop_column('users', 'scholarship_interest')
    op.drop_column('users', 'ranking_preference')
    op.drop_column('users', 'intake_preference')
    op.drop_column('users', 'budget_inr')
    op.drop_column('users', 'work_experience_years')
    op.drop_column('users', 'gmat_score')
    op.drop_column('users', 'gre_score')
    op.drop_column('users', 'toefl_score')
    op.drop_column('users', 'english_test')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'home_university')
    op.drop_column('users', 'current_degree')
    op.drop_index(op.f('ix_universities_subject'), table_name='universities')
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consultation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('appointments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    # ### end Alembic commands ###
